akashic-games/game-driver

- CHANGELOG.md
- package.json
- src/Game.ts
https://github.com/akashic-games/akashic-engine/pull/124 の実装修正です。
`g.game.getCurrentTime()` の戻り値が整数になるよう変更します。
これは、上記メソッドを `Date.now()` の代わりにakashicコンテンツ内で使うため、互換性を取るための措置です。
- あり
従来小数で返されていた値が、今後は整数で返るようになります。
> fix getCurrentTime

- CHANGELOG.md
- package.json
- src/Game.ts
https://github.com/akashic-games/game-driver/pull/10 の実装修正では正しく整数化されないケースが存在したため、これを修正します。
- なし
> Fix bitshift getcurrenttime

- CHANGELOG.md
- package.json
- spec/src/auxiliary/MemoryAmflowClientSpec.ts
- src/auxiliary/MemoryAmflowClient.ts
* 送信したプレイログ情報と保持しているプレイログ情報が同じものになっていることで問題が発生することがあったので、MemoryAmflowClient のプレイログ情報保存時にデータを deep cloneするように修正しました。
* `MemoryAmflowClient#sendTick` と `MemoryAmflowClient#sendEvent`で取得したデータをlodash.clonedeepを用いてdeep clone
> MemoryAmflowClientのプレイログ情報をcloneして保持するようにする修正

- .npmrc
- package.json
- spec/src/GameLoopSpec.ts
- src/Clock.ts
- src/GameLoop.ts
- src/ProfilerClock.ts
pdi 層から looper が長時間呼ばれなかった場合 (e.g: ウェブブラウザにおいてタブをバックグラウンドに長時間切り替えていたなど) 、その後 looper が再開された際に skip threshold を超えていたら skip 扱いとするように修正します。
> Make skip when game looper has been stopped above SKIP_THRESHOLD

- CHANGELOG.md
- package.json
- src/EventConverter.ts
playlog <-> g.Event の変換処理において evenfFlags (旧 priority) をマスクしないように修正します。
> Don't mask event flags

- spec/src/EventBufferSpec.ts
- src/EventBuffer.ts
掲題どおり。
未対応であることに気づいたので実装を加えます。
ついでに `TimestampEvent` のテストも一部なかったので追加しました。
> fix: support PlayerInfoEvent in isEventLocal()

- CHANGELOG.md
- package.json
`build` 以下のビルド成果物が壊れていたバグを修正します。
本修正後、適当なブラウザ (`require()` が存在しない環境) で `require("@akashic/game-driver")` がエラー無く実行できることを確認。
```html
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<title>no title</title>
</head>
<body>
<script src="./build/akashic-engine.js"></script>
<script src="./build/game-driver.js"></script>
</body>
</html>
```
> Fix build script

- CHANGELOG.md
- package.json
- spec/src/GameLoopSpec.ts
- src/GameLoop.ts
- src/TickBuffer.ts
[ignorable イベント](https://github.com/akashic-games/playlog/pull/8) に対応します。
「リプレイする上で必ずしも再現する必要のないイベント」と定義しています。game-driver においてはスキップ中に除外することを試みます。ただし、条件によってはスキップ中でも ignorable イベントを含むティックが消化されることがあります (e.g. 既に ignorable イベントを取得済みの場合に未来にシークした場合など)。
最新に追いつくまで ignorable イベントを除外したティックを消化します。
1. 最初に ignorable イベントを除外した状態のティックを取得します。
2. シーク位置 (目標時刻) に到達したら手持ちのティックを削除し、ignorable イベントを含めたティックを取得します。
> ignorable イベントに対応

- package.json
- src/TickBuffer.ts
`TickBuffer#dropAll()` の呼び出し時に `TickBuffer#currentTime` と `TickBuffer#_nearestAbsentAge` の値をリセットするように修正します。それにより `TickBuffer#consume()` の呼び出し時に `TickBuffer#currentAge !== TickBuffer#_nearestAbsentAge` かつ `TickBuffer#_tickRanges.length === 0` というケース (e.g. 追っかけ再生時にちょうどティックの直前あたりにシークした際など) が発生し、ランタイムエラーとなっていた問題を修正します。
> TickBuffer#dropAll() の呼び出し時に内部状態をリセットするように修正

- CHANGELOG.md
- package.json
- spec/src/GameLoopSpec.ts
- src/TickBuffer.ts
過渡期のため、一時的に `TickBuffer#requestTicks()` 内で @akashic/amflow@2 以前の `AMFlow#getTickList()` の引数を利用するように差し戻します。
akashic-cli-serve@1.5.4 にて動作確認済みです。
> revert: use deprecated interface

- CHANGELOG.md
- spec/src/TickBufferSpec.ts
- src/TickBuffer.ts
掲題どおり。 `gotNoTickTrigger` の fire 条件に誤りがありました。修正に併せてユニットテストを追加します。(#105 の後に直すつもりでしたが、テストでこの修正を前提にしてしまったので、 #105 への PR になっています)
なおたまたまですが外部影響はないはずです。
というのも、この問題は「ティックを取得した時、"何も得られなかった時" ではなく "イベントを持つティックがなかった時" に `gotNoTickTrigger` を fire していた」ものでした。つまり「後続ティックが取得できた ("あった") のに、間違って "なかった" (no tick) と通知するケース」がありました。
一方この trigger の fire の前には `gotNextTickTrigger` の fire 処理があります。その影響で [「後続ティックがあった場合」には必ず `GameLoop#_waitingNextTick` が落ちます][wait-end] (未使用のオプション `FrameByFrame` を除き)。一方この `gotNoTickTrigger` の通知を受ける `GameLoop#_onGotNoTick()` は [「 `_waitingNextTick` ならば `_consumedLatestTick` を立てる」処理しかしていません][set-consumed]。そのため `gotNoTickTrigger` が誤通知するケースでは (正しく) なんの処理も走りませんでした。(gotNextTickTrigger の fire 順に救われた形)
[wait-end]: https://github.com/akashic-games/game-driver/blob/main/src/GameLoop.ts#L734 …
> fix: avoid wrong fire of TickBuffer#gotNoTickTrigger

- CHANGELOG.md
- spec/src/TickBufferSpec.ts
- src/TickBuffer.ts
掲題どおり。 `TickBuffer#setCurrentAge()` で `currentAge` を更新する際、 `knownLatestAge` (既知の最新 age) の更新が漏れていました。
この影響で、最新の tick の消化を目指す `Realtime` モードの動作に支障が出る場合があります。「最新」の基準としてこの `knownLatestAge` を参照するためです。この値を更新しそこなうと「実行開始前に `setCurrentAge()` で現在 age を進めたにも関わらず、(更新されていない)  `knownLatestAge` を参照して age: 0 に戻ってしまい、そこから改めて最新を目指す」現象が発生します。これを修正します。
なおこの現象は、以下の両方を満たす時にのみ発生します。
- (a) このインスタンスの既知の最新 tick よりも未来に `setCurrentAge()` している場合
- (b) tick の push 通知が受け取れなかった場合
- (アクティブインスタンスが一時停止している、存在しない、または遅延で受信が遅れたなど)
従来は (a) の条件を満たすことがありませんでした。スナップショットによって (a) を満たす「スナップショットから実行を開始する」ケースが生まれたために露見しました。
ユニットテストの追加のほか、 akashic-cli@2.11.5 の serve に組み込み、この処理を利用するパスの動作を目視確認しています。実際にはさらに別件の問題が現れますが、そちらは別 PR で対応します。
> fix: update TickBuffer#knownLatestAge in setCurrentAge()

- CHANGELOG.md
- spec/src/GameLoopSpec.ts
- spec/src/TickBufferSpec.ts
- src/GameLoop.ts
- src/TickBuffer.ts
Realtime モードのパッシブインスタンスをスナップショットから開始した時、 しばらくゲームが進まない問題を解消します。
Realtime モードは、最新 tick の受信を契機に、その最新 tick の消化を最速で目指すモードです。逆に最新 tick を受信しない限り動きません。
従来の Realtime モードは、 [実行開始直後 (`currentAge === 0` の時) に、能動的に後続 tick を取得していました][req-on-age0] (a) 。ある種の条件で、実行開始後に最新 tick が長時間受信できないケースがあったためです。しかしスナップショットから開始すると、実行開始直後であっても (`currentAge > 0` になるので) このパスに入れません。そのため最新 tick の受信が長時間起きない状況ではしばらくゲームが進まなくなりました。(ポーリング処理による tick 受信が起きる 10 秒後に動き出します)
そもそも、現在の (a) の振る舞いは正しいものではないように思えます。
というのも極端なケースでは、一度の後続 tick 要求で tick が取得しきれるとは限りません。また一度目で取得した tick の消化中に、別の最新 tick を受信できるとも限りません。そのためごく稀なケースでは `currentAge > 0` であっても後続 tick を要求しなければならないことが元々あり得ました。(現実的には、さらに [別のパス][another-req-path] での tick 要求も生じなかった時にしか問題にならないので、意図的に再現するのは非常に手間ですが)
スナップショットの導入により、その非常に稀だった問題を確実に再現できるようになったのが現状です。
[req-on-age0]: …
> fix: fix handling the latest tick. introduce _foundLatestTick

- CHANGELOG.md
- jest.config.js
- package.json
- spec/src/TickBufferSpec.ts
- src/GameLoop.ts
- src/TickBuffer.ts
掲題どおり。ゲーム実行開始直後のスキップ時、それがごく短い (通常であればスキップ状態に入らないほど短い) 早回しである場合、音声の再生速度変更 (＝SEのミュート) をしないようにします。
歴史的経緯から、ゲームの実行開始直後には必ず一度スキップ状態になります。スキップ状態では SE ("sound" のオーディオアセット) はミュートされます。passive インスタンスは開始時に active インスタンスから十フレーム程度遅れていることが多く、そのため開始直後に再生された SE がミュートされてしまうことがありました。この PR はこの問題を修正します。
これらは Akashic 用語です。ゲームの最新状態に追いつく必要がある時、game-driver は 1 フレーム時間の間に複数 tick を消化します。これを "早回し" といいます 。早回しで消化する tick が閾値より多い (遅れが大きい) 場合、game-driver はこれをコンテンツに通知します。これを "スキップする" (または "早送りする") といいます。スキップ開始通知からスキップ終了通知までの間を、スキップ状態と呼びます。言い換えるとスキップは「コンテンツに通知されるほど長い早回し」です。
ただし上述のとおり歴史的経緯から、ゲームの実行開始時には、遅れの程度にかかわらず必ず一度スキップします。
これは程度問題です。マルチプレイに参加する時、ゲームプレイの最新状態に追いつくために早回しは不可避であり、この時 SE はミュートされないと不快です (大量の SE が短時間に再生される) 。他方ですぐに追いつく、極論気づかれない程度の早回しでは、 ミュートされる方が不自然です。その境界は機械的に定まるものではありません。 …
> fix: avoid audio playback rate changes for small age-zero-skip

- CHANGELOG.md
- package.json
- src/Game.ts
- src/__tests__/Game.spec.ts
- src/__tests__/fixtures/simple_game/script/main.js
- src/__tests__/helpers/MockGame.ts
- src/__tests__/helpers/prepareGame.ts
掲題どおり。
スナップショットからの復元時、起動引数が渡されていませんでした。起動引数は実行環境に依存する値なので、「スナップショットからの復元時にそれを参照していいかどうか」はエンジン本体には決められないものでした。通常起動時と同様そのまま引き渡すようにします。
> fix: pass game arguments even with snapshot

- .github/workflows/reftest.yml
Actions の set-output コマンドが廃止となるため、$GITHUB_OUTPUT を利用するように修正。
> Fix set-output command in Actions

- src/Game.ts
- src/ProfilerClock.ts
- src/__tests__/helpers/MockGame.ts
- src/__tests__/helpers/MockResourceFactory.ts
- tsconfig.json
#200 のようなトラブルを軽減するため、 `noImplicitOverride` を有効にします。
> chore: enable noImplicitOverride

- CHANGELOG.md
- package-lock.json
- package.json
- src/Game.ts
- src/GameDriver.ts
- src/GameLoop.ts
- src/ProfilerClock.ts
- src/__tests__/Game.spec.ts
- src/__tests__/GameLoop.spec.ts
- src/__tests__/helpers/MockGame.ts
- src/__tests__/helpers/MockResourceFactory.ts
- tsconfig.json
掲題どおり。 `Game#handlerSet` を `Game#rawHandlerSet` に改名し、祖先クラス `g.Game#handlerSet` のオーバーライドをしないように変更します。
main 最新の game-driver を akashic serve に組み込むと、 「新規プレイ」ボタンを押すたびに次のようなエラーが出ます。
```
engineFilesV3_7_3_Canvas.js:4140 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'changeSceneMode')
at Game._handleSceneChanged (engineFilesV3_7_3_Canvas.js:4140:25)
at Trigger.fire (engineFilesV3_7_3_Canvas.js:17889:36)
at Game._doPopScene (engineFilesV3_7_3_Canvas.js:4280:33)
at Game._flushPostTickTasks (engineFilesV3_7_3_Canvas.js:4188:30)
at Game._destroy (engineFilesV3_7_3_Canvas.js:3962:22)
at Game._destroy (engineFilesV3_7_3_Canvas.js:11050:35)
(snip)
```
確認するとこの例外は以前から throw されていました。しかし es6-promise が握りつぶしてたらしく (詳細未確認)、 #199 以降に露出するようになったようです。
(以下、`Game` と `g.Game` …
> fix: rename/avoid a property override to fix duplicated destroy

- CHANGELOG.md
- package.json
- src/TickGenerator.ts
- src/__tests__/TickGenerator.spec.ts
#203 で `readJoinLeaveEvents()` を呼び出す箇所ごと消えた結果、 join/leave 両イベントがロストしていました。これを修正します。
ユニットテストを加える他、手元のマルチプレイコンテンツがこの変更後動作することを akashic serve で目視確認しています。
> fix: fix lost join/leave

- CHANGELOG.md
- package-lock.json
- package.json
- src/GameDriver.ts
掲題どおり。
通常必要ないパスですが、`changeState()` のコールバックが省略されるケースを受け付けます。
修正自明につきセルフマージします。
> fix: accept changeState() without callback

- CHANGELOG.md
- package-lock.json
- package.json
- src/Clock.ts
- src/EventBuffer.ts
- src/GameHandlerSet.ts
- src/GameLoop.ts
- src/__tests__/Clock.spec.ts
- src/__tests__/EventBuffer.spec.ts
https://github.com/akashic-games/akashic-engine/pull/524 の game-driver 側対応です。
- `GameHandlerSet#suspendLocalTick()`, `resumeLocalTick()` を実装
- コンテンツ側からの任意のタイミングでクロックを再開/停止
- Passive Realtime のインスタンスのみ対応
- `Clock#suspend()`, `Clock#resume()` を追加
- `GameLoop#suspend()`, `GameLoop#resume()` を追加
- `EventBuffer#onLocalEventReceive` を追加
- `GameLoop#_localAdvanceTime` の更新タイミングを一部修正
クロックの停止時、次のいずれかの契機によりクロックを再開します。
1. tick の受信時
2. local event の受信時
3. `GameLoop#setLoopConfiguration()`, `GameLoop#setExecutionMode()`
- Realtime -> Replay または Passive -> Active 切替時など
> feat: support suspending and resuming the clock
