akashic-games/game-driver

CHANGELOG.md
package.json
src/GameDriver.ts

https://github.com/akashic-games/game-driver/pull/2 と同じ対応をv1系でも行いました

コンテンツがdestroy済みならPromise内の処理を止めるようにする対応(v1系)

---

package.json

https://github.com/akashic-games/game-driver/pull/6 でpackage.jsonのversionを更新し忘れていたので対応しました

package.jsonのversionを0.11.22に更新

---

CHANGELOG.md
package.json
spec/helpers/src/MockAmflow.ts
src/GameDriver.ts
src/GameLoop.ts
src/JoinResolver.ts
src/StorageResolver.ts
src/TickBuffer.ts
src/auxiliary/MemoryAmflowClient.ts
src/auxiliary/ReplayAmflowProxy.ts

amflowのminor更新によるバージョンアップ(minor version)
- amflowのfunctionを使用している箇所を、amflow@0.3.1のfunctionの形に合わせるよう修正

Update by minor version-up of amflow

---

CHANGELOG.md
package.json
src/Game.ts

https://github.com/akashic-games/akashic-engine/pull/127 の実装です。

Add Game#isActiveInstance

---

CHANGELOG.md
package.json
spec/src/auxiliary/MemoryAmflowClientSpec.ts
src/auxiliary/MemoryAmflowClient.ts

https://github.com/akashic-games/game-driver/pull/14 と同様の修正をv1側でも行いました。

MemoryAmflowClientのプレイログ情報をcloneして保持するよう修正(v1)

---

CHANGELOG.md
package.json
spec/src/GameSpec.ts
src/Game.ts

* akashic-engine側の変更( https://github.com/akashic-games/akashic-engine/pull/137 )に合わせてgame-driver側も修正

Game#_terminateGame() を Game#_abortGame() にリネームする対応

---

.travis.yml
CHANGELOG.md
package.json
spec/src/GameSpec.ts
src/Game.ts

* akashic-engine側の変更( https://github.com/akashic-games/akashic-engine/pull/138 )に合わせてgame-driver側も修正

Game#_terminateGame() を Game#_abortGame() にリネームする対応(v1)

---

CHANGELOG.md
package.json
src/GameDriver.ts
src/GameLoop.ts

`g.Game#modified` のfunction化に伴い、`g.Game#modified()`の呼び出しに修正

Change g.Game#modified to function

---

CHANGELOG.md
package.json

依存しているplaylogとamflowのメジャーバージョンを更新する対応を行いました

update inner modules (v1.8.0)

---

CHANGELOG.md
package.json

依存しているplaylogとamflowのメジャーバージョンを更新する対応を行いました

update inner modules (v0.14.0)

---

package.json
spec/helpers/src/prepareGame.ts
spec/src/GameLoopSpec.ts
spec/src/GameSpec.ts
src/EventBuffer.ts
src/Game.ts
src/GameDriver.ts
src/GameLoop.ts
src/StartPointData.ts

https://github.com/akashic-games/akashic-engine/pull/183 に追従します。

Support changes for g.Game

---

.gitignore
package.json
spec/helpers/src/prepareGame.ts
spec/src/GameLoopSpec.ts
spec/src/GameSpec.ts
src/Game.ts
src/GameDriver.ts
src/GameHandlerSet.ts
src/GameLoop.ts

https://github.com/akashic-games/akashic-engine/pull/190 に対応します。

Support g.GameHandlerSet

---

package.json
spec/src/GameLoopSpec.ts
src/EventBuffer.ts
src/Game.ts
src/GameHandlerSet.ts
src/GameLoop.ts

https://github.com/akashic-games/akashic-engine/pull/192 の変更に追従します。
* なし

Follow the new interface of g.Game

---

package.json
src/EventBuffer.ts
src/GameLoop.ts

https://github.com/akashic-games/akashic-engine/pull/199 にて追加した `g.Game#resolvePointEvent()` を利用するようにします。

Use g.Game#resolvePointEvent()

---

CHANGELOG.md
package.json
spec/fixtures/local_tick_game/script/main.js
spec/fixtures/simple_game/script/main.js
spec/helpers/src/MockGame.ts
spec/helpers/src/MockResourceFactory.ts
src/GameHandlerSet.ts
src/GameLoop.ts

掲題どおり。 akashic-games/akashic-engine#211 に追従します。
追記: CI 落ちていますが akashic-engine を反映できないためです。手元では akashic-games/pdi-browser#69 と組み合わせて akashic-sandbox で最低限のコンテンツの動作を確認しています。

follow akashic-engine #211 (enum to string literal types)

---

CHANGELOG.md
package.json
spec/src/auxiliary/MemoryAmflowClientSpec.ts
src/auxiliary/MemoryAmflowClient.ts

MemoryAMFlow の実装を https://github.com/akashic-games/playlog/pull/6 の仕様に合わせます。
参考
* https://github.com/akashic-games/amflow/pull/6

Support transient event

---

.gitignore
CHANGELOG.md
package.json
spec/src/EventBufferSpec.ts
spec/src/auxiliary/MemoryAmflowClientSpec.ts
src/EventBuffer.ts
src/EventConverter.ts
src/EventIndex.ts
src/EventPriority.ts
src/GameDriver.ts
src/auxiliary/MemoryAmflowClient.ts

https://github.com/akashic-games/playlog/pull/6 に追従します。
MemoryAMFlow の transient event 実装

Follow playlog@3.0.0

---

CHANGELOG.md
package.json
spec/helpers/src/MockPlatform.ts
spec/helpers/src/MockResourceFactory.ts
spec/src/EventBufferSpec.ts
src/Clock.ts
src/EventBuffer.ts
src/GameDriver.ts
src/GameLoop.ts
src/PdiUtil.ts
src/TickGenerator.ts

https://github.com/akashic-games/akashic-pdi/pull/16 に追従します。
特にコメントした点以外は、単純な型名変更への追従です。

use the integrated pdi

---

CHANGELOG.md
package.json
spec/helpers/src/MockAmflow.ts
src/auxiliary/MemoryAmflowClient.ts
src/auxiliary/ReplayAmflowProxy.ts

以下のモジュール更新に追従します。
* `@akashic/akashic-pdi@2.10.0`
* https://github.com/akashic-games/akashic-pdi/pull/19
* `@akashic/amflow@3.0.0`
* https://github.com/akashic-games/amflow/pull/8
* 一旦は旧インタフェースのみをサポートするようにします。
* `@akashic/playlog@3.1.0`
* https://github.com/akashic-games/playlog/pull/8

Follow @akashic/amflow@3.0.0

---

CHANGELOG.md
package.json
spec/src/EventBufferSpec.ts
src/EventBuffer.ts

akashic-games/akashic-engine#254 に追従します。

Follow akashic-engine@3.0.0-beta.35

---

.travis.yml
CHANGELOG.md
package.json
spec/src/EventBufferSpec.ts
src/EventBuffer.ts

* akashic-games/akashic-engine#255 の変更に追従します。
* travis-ci の Node.js のバージョンを 10 -> 14 に変更します。

Follow akashic-engine@3.0.0-beta.36

---

CHANGELOG.md
package.json

`build` 以下に `@akashic/akashic-engine` の実装が含まれていたバグを修正します。

Extern @akashic/akashic-engine from build script

---

CHANGELOG.md
package.json
src/GameDriver.ts

#49 にて permission を取得するより前に permission の存在チェックを行ってしまっていたため、常にエラーとなってしまっていたバグを修正します。

fix: drop permission validation

---

CHANGELOG.md
package.json

game-configuration@1.0.1 に更新します。

chore(deps): use game-configuration@1.0.1

---

package.json
spec/helpers/src/MockAmflow.ts
spec/helpers/src/prepareGame.ts
spec/src/GameLoopSpec.ts
spec/src/auxiliary/MemoryAmflowClientSpec.ts
spec/src/auxiliary/ReplayAmflowProxySpec.ts
spec/support/jasmine.json
src/ExcludeEventFlags.ts
src/GameLoop.ts
src/TickBuffer.ts
src/auxiliary/MemoryAmflowClient.ts
src/auxiliary/ReplayAmflowProxy.ts

* AMFlow@3.0.0 に対応したインタフェースを利用するように仮対応
* https://github.com/akashic-games/amflow/pull/8
* リアルタイム動作時の初回 playlog 読み込みから ignorable フラグが付いたイベントを削除するように

AMFlow@3.0.0 に対応したインタフェースを利用するように仮対応

---

CHANGELOG.md
package-lock.json
package.json
spec/src/ClockSpec.ts
src/Clock.ts

_onLooperCall の引数に NaN が渡された場合に 次フレームまで進行するように修正。

Modify to advance next frame when the argument of _onLooperCall is NaN

---

CHANGELOG.md
package-lock.json
package.json

v2.3.0; use pdi-types@1.2.0

---

.github/workflows/release.yml
package-lock.json
package.json
spec/helpers/src/MockResourceFactory.ts

以下の変更に追従します。
* https://github.com/akashic-games/pdi-types/pull/20
* https://github.com/akashic-games/game-configuration/pull/7
* https://github.com/akashic-games/pdi-common-impl/pull/19
* https://github.com/akashic-games/akashic-engine/pull/311

feat: follow feature tag

---

CHANGELOG.md
package.json
spec/src/GameLoopSpec.ts
src/TickBuffer.ts

#62 の revert を解除します。
自明につきセルフマージします。

v2.3.1; revert v2.1.1 to re-enable amflow@3 interface

---

CHANGELOG.md
package.json

bump version: v2.4.1

---

CHANGELOG.md
package-lock.json
package.json

掲題どおり。
肝心の dependencies の更新が漏れていた #111 を修正します。

fix: v2.6.0; fix forgottten dependencies update

---

package-lock.json
package.json
src/Clock.ts
src/DriverConfiguration.ts
src/EventBuffer.ts
src/Game.ts
src/GameDriver.ts
src/GameHandlerSet.ts
src/GameLoop.ts
src/JoinResolver.ts
src/LoopConfiguration.ts
src/ProfilerClock.ts
src/StorageFunc.ts
src/StorageOnTick.ts
src/StorageResolver.ts
src/TickBuffer.ts
src/TickController.ts
src/TickGenerator.ts
src/auxiliary/SimpleProfiler.ts

eslint-config@1.1.0 による自動修正と lint エラーの修正
- import type の使用
- const を使用できる箇所を const へ
renovate の PR #121   へマージします。

Fix by eslint, lint error

---

.github/workflows/reftest.yml

rel: https://github.com/akashic-games/akashic-engine/pull/383

fix: engine-files の reftest が通るように修正

---

.github/workflows/reftest.yml
.github/workflows/release.yml
.github/workflows/test.yml
renovate.json

* CI の Node のバージョンを 14, 16 系に更新
* renovate.json を共通設定に変更

chore: ワークフローの修正など

---

.github/workflows/release.yml
CHANGELOG.md
package-lock.json
package.json

akashic-engine@3.5.0-beta.1 に追従します。
内部モジュールの更新のみのためセルフマージします。

feat: follow akashic-engine@3.5.0-beta.1

---

CHANGELOG.md
package-lock.json
package.json

`akashic-engine@3.5.0-beta.2` に追従します。

feat: follow akashic-engine@3.5.0-beta.2

---

CHANGELOG.md
package-lock.json
package.json

akashic-engine を 3.6.0 に更新します。パッケージのみの更新のためセルフマージします。

chore: follow akashic-engine@3.6.0

---

jest.config.js

ts-jest@29 の更新による jest 更新による jest.config.js の修正。
renovateの #162 へセルフマージします。

Mod jest.config

---

CHANGELOG.md
package-lock.json
package.json
src/__tests__/helpers/MockResourceFactory.ts

feat: v2.10.0; follow akashic-engine@3.7.0

---

CHANGELOG.md
package-lock.json
package.json
src/GameLoop.ts

https://github.com/akashic-games/akashic-engine/pull/427 の game-driver 側の対応です。
https://github.com/akashic-games/akashic-engine/pull/427 のミニマムコンテンツが動作することを確認しています。
akashic-engine 側のマージ後に package.json 等を更新します。

feat: akashic-engine@3.9.0 に追従

---

CHANGELOG.md
package-lock.json
package.json

* @akashic/akashic-engine@3.10.0 に追従
* @akashic/game-configuration@1.9.0 に追従
自明な変更のためセルフマージします。

feat: follow akashic-engine@3.10.0

---

CHANGELOG.md
package-lock.json
package.json

chore: bump v2.13.0

---

.github/workflows/reftest.yml
.github/workflows/release.yml
.github/workflows/test.yml

Update CI node version

---

CHANGELOG.md
package-lock.json
package.json

akashic-engine@3.12.0 に追従します。自明な修正のためセルフマージします。

chore(deps): update akashic-engine@3.12.0

---

CHANGELOG.md
package.json
spec/src/EventBufferSpec.ts
spec/src/GameLoopSpec.ts
spec/src/StorageResolverSpec.ts

* @akashic/amflowと@akashic/playlogと@akashic/akashic-pdiのminor更新
* typescriptを最新のバージョンに
* それに伴ってspec以下のコードも修正

update akashic modules

---

CHANGELOG.md
package.json
spec/src/EventBufferSpec.ts
spec/src/StorageResolverSpec.ts

#193 の v1 側対応です。
自明につきセルフマージします。

Follow @akashic/akashic-pdi@1.16.0 (ae1x-master)

---

CHANGELOG.md
package-lock.json
package.json

`akashic-engine@3.14.0` に更新します。モジュールのバージョン更新のみで自明な修正のためセルフマージします。

chore: follow akashic-engine@3.14.0

---

package-lock.json
package.json
src/GameDriver.ts

Remove es6-promise

---

.github/workflows/reftest.yml
.github/workflows/test.yml
CHANGELOG.md
package-lock.json
package.json
src/__tests__/EventBuffer.spec.ts

* 内部モジュールを更新します。
* 一部テストを修正します。
* CI の Node のバージョンを更新します。

chore(deps): update internal modules

---

CHANGELOG.md
package-lock.json
package.json
src/GameDriver.ts

https://github.com/akashic-games/akashic-engine/pull/510 に追従します。
モジュールの更新と型の修正のみのためセルフマージします。

Update akashic engine 3.19.0

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/akashic-games/akashic-engine/pull/515 に追従します。
モジュールの更新のみのためセルフマージします。

Update akashic engine 3.20.0
